---
- hosts: '{{ hosts | default("all") }}'
  become: '{{ become | default("no") }}'
  become_user: '{{ become_user | default("root") }}'
  remote_user: '{{ remote_user | default("root") }}'
  tasks:
      - name: Check which version we are running
        command: "/bin/sh -c 'atomic host status'"
        ignore_errors: True
        register: atomic_version
        changed_when: False
