---
# run playbooks based on certain params
skip_prereqs: false
setup_minishift: true
setup_pipeline: true
setup_jenkins: true
setup_containers: true

# default location for minishift
minishift_dest_dir: "{{ ansible_env.HOME }}/minishift"

# default minishift profile name
profile: minishift

# disk and memory size
disk_size: 40gb
memory: 6400mb

# minishift iso location
minishift_iso: http://artifacts.ci.centos.org/fedora-atomic/minishift/iso/minishift.iso

# repo to clone
pipeline_repo: https://github.com/CentOS-PaaS-SIG/ci-pipeline

# repo directory
pipeline_dir: "{{ ansible_env.HOME }}/minishift/ci-pipeline"

# cluster username
username: developer

# cluster password
password: developer

# modify tags on images
modify_tags: true

# tag to use
tag: stable

# modify security context contraints (SCC) to run privileged containers
modify_scc: true