- builder:
    name: ci-pipeline-duffy-builder
    builders:
        - macro-cciskel-duffy-prepared-allocate:
            jobclass: builder
            duffytimeoutsecs: 3600
            playbook: sig-atomic-buildscripts/centos-ci/setup/setup-system.yml
        - shell: |
            #!/bin/bash
            set -xeuo pipefail

            (echo -n "export RSYNC_PASSWORD=" && cat ~/duffy.key | cut -c '-13') > rsync-password.sh
            cat >>task.env <<EOF
            export JENKINS_JOB_NAME="${{JOB_NAME}}"
            export JENKINS_BUILD_TAG="${{BUILD_TAG}}"
            export OSTREE_BRANCH="${{OSTREE_BRANCH:-}}"
            EOF
            cat task.env

            rsync -Hrlptv --stats -e ssh task.env rsync-password.sh builder@${{DUFFY_HOST}}:
            for repo in aos-ci sig-atomic-buildscripts; do
                rsync -Hrlptv --stats --delete -e ssh $repo/ builder@${{DUFFY_HOST}}:/$repo
            done

            build_success=true
            if ! ssh -tt builder@${{DUFFY_HOST}} ". task.env && ./aos-ci/tasks/{task}"; then
                build_success=false
            fi

            # Currently we don't have any logs being generated
            #rsync -Hrlptv --stats -e ssh builder@${{DUFFY_HOST}}:logs/ $WORKSPACE/logs || true
            # Exit with code from the build
            if test "${{build_success}}" = "false"; then
                echo 'Build failed, see logs above'; exit 1
            fi

- publisher:
    name: ci-pipeline-duffy-publisher
    publishers:
        - archive:
            artifacts: 'logs/**'
            allow-empty: 'true'
        - macro-cciskel-duffy-deallocate

- job:
    name: ci-pipeline-ostree-compose
    defaults: ci-pipeline-defaults
    builders:
        - ci-pipeline-duffy-builder:
            task: ostree-compose

    publishers:
        - ci-pipeline-duffy-publisher
