- publisher:
    name: ci-pipeline-ostree-boot-trigger
    publishers:
        - trigger-parameterized-builds:
            - project: ci-pipeline-ostree-boot-sanity
              current-parameters: true
              property-file: ${WORKSPACE}/logs/ostree.props
              block: false
              same-node: true

- publisher:
    name: ci-pipeline-ostree-image-trigger
    publishers:
        - postbuildscript:
            builders:
                - conditional-step:
                    condition-kind: shell
                    condition-command: |
                        prev=0
                        number=$(curl $JENKINS_URL/job/{compose_job}/lastBuild/api/json 2>/dev/null | jq '.number')
                        for ((i=$number; i>0; i--)); do
                            branch=$(curl $JENKINS_URL/job/{compose_job}/$i/api/json 2>/dev/null | jq -r '.actions[] | select(.parameters).parameters[] | select(.name | contains("fed_branch")).value')
                            if [ "$branch" = "$fed_branch" ]; then
                                result=$(curl $JENKINS_URL/job/{compose_job}/$i/api/json 2>/dev/null| jq -r '.result')
                                if [ "$result" = "SUCCESS" ]; then
                                    prev=$(curl $JENKINS_URL/job/{compose_job}/$i/api/json 2>/dev/null| jq '.timestamp' | cut -c1-10)
                                    break
                                fi
                            fi
                        done
                        cur=$(date +%s)
                        elapsed=$((cur - prev))
                        if [ $elapsed -gt 86400 ]; then
                           exit 0
                        fi
                        exit 1
                    on-evaluation-failure: dont-run
                    steps:
                          - trigger-builds:
                            - project: '{compose_job}'
                              current-parameters: true
            script-only-if-succeeded: false

- job:
    name: ci-pipeline-ostree-compose
    defaults: ci-pipeline-defaults
    parameters:
        - string:
            name: fed_branch
            description: |
              which branch to build
        - string:
            name: rev
            description: |
              which revision of the package being updated
        - string:
            name: fed_repo
            description: |
              which repo of the package being updated
    builders:
        - shell: |
            if [ "$fed_branch" = "master" ]; then
                echo "fed_branch=rawhide" > ${WORKSPACE}/job.properties
            fi
        - inject:
            properties-file: ${WORKSPACE}/job.properties
        - jms-messaging:
            override-topic: org.centos.prod.ci.pipeline.compose
            provider-name: fedmsg
            msg-type: Custom
            msg-props: |
                topic=org.centos.prod.ci.pipeline.compose.running
                username=fedora-atomic
            msg-content: |
                {
                    "build_url": "${BUILD_URL}",
                    "compose_url": "http://artifacts.ci.centos.org/artifacts/fedora-atomic/${fed_branch}/ostree",
                    "compose_rev": "",
                    "build_id": "${BUILD_ID}",
                    "ref": "fedora/${fed_branch}/x86_64/atomic-host",
                    "rev": "${rev}",
                    "namespace": "rpms",
                    "repo": "${fed_repo}",
                    "status": "success",
                    "test_guidance": ""
                }
        - ci-pipeline-duffy-builder:
            task: ostree-compose
            variables: |
                export BUILD="${fed_branch}"
                export JENKINS_JOB_NAME="${JOB_NAME}"
                export JENKINS_BUILD_TAG="${BUILD_TAG}"
                export OSTREE_BRANCH="${OSTREE_BRANCH:-}"
            playbook: sig-atomic-buildscripts/centos-ci/setup/setup-system.yml
        - inject:
            properties-file: ${WORKSPACE}/logs/ostree.props
    publishers:
        - ci-pipeline-duffy-publisher
        - jms-messaging:
            override-topic: org.centos.prod.ci.pipeline.compose
            provider-name: fedmsg
            msg-type: Custom
            msg-props: |
                topic=org.centos.prod.ci.pipeline.compose.complete
                username=fedora-atomic
            msg-content: |
                {
                    "build_url": "${BUILD_URL}",
                    "compose_url": "http://artifacts.ci.centos.org/artifacts/fedora-atomic/${fed_branch}/ostree",
                    "compose_rev": "${commit}",
                    "build_id": "${BUILD_ID}",
                    "ref": "fedora/${fed_branch}/x86_64/atomic-host",
                    "rev": "${rev}",
                    "namespace": "rpms",
                    "repo": "${fed_repo}",
                    "status": "${BUILD_STATUS}",
                    "test_guidance": ""
                }
        - ci-pipeline-ostree-boot-trigger
        - ci-pipeline-ostree-image-trigger:
            compose_job: ci-pipeline-ostree-image-compose

- job:
    name: ci-pipeline-ostree-image-compose
    defaults: ci-pipeline-defaults
    parameters:
        - string:
            name: fed_branch
            description: |
              which branch to build
        - string:
            name: commit
            description: |
              sha pointing to the particular commit we want to test
    builders:
        - shell: |
            if [ "$fed_branch" = "master" ]; then
                echo "fed_branch=rawhide" > ${WORKSPACE}/job.properties
            fi
        - inject:
            properties-file: ${WORKSPACE}/job.properties
        - jms-messaging:
            override-topic: org.centos.prod.ci.pipeline.image
            provider-name: fedmsg
            msg-type: Custom
            msg-props: |
                topic=org.centos.prod.ci.pipeline.image.running
                username=fedora-atomic
            msg-content: |
                {
                    "build_url": "${BUILD_URL}",
                    "image_url": "",
                    "image_name": "",
                    "build_id": "${BUILD_ID}",
                    "ref": "fedora/${fed_branch}/x86_64/atomic-host",
                    "rev": "N/A",
                    "namespace": "rpms",
                    "repo": "N/A",
                    "compose_url": "http://artifacts.ci.centos.org/artifacts/fedora-atomic/${fed_branch}/ostree",
                    "compose_rev": "${commit}",
                    "status": "success",
                    "test_guidance": "",
                    "type": "qcow2"
                }
        - ci-pipeline-duffy-builder:
            task: ostree-image-compose
            variables: |
                export BUILD="${fed_branch}"
                export JENKINS_JOB_NAME="${JOB_NAME}"
                export JENKINS_BUILD_TAG="${BUILD_TAG}"
                export OSTREE_BRANCH="${OSTREE_BRANCH:-}"
            playbook: sig-atomic-buildscripts/centos-ci/setup/setup-system.yml
        - inject:
            properties-file: ${WORKSPACE}/logs/ostree.props
    publishers:
        - ci-pipeline-duffy-publisher
        - jms-messaging:
            override-topic: org.centos.prod.ci.pipeline.image
            provider-name: fedmsg
            msg-type: Custom
            msg-props: |
                topic=org.centos.prod.ci.pipeline.image.complete
                username=fedora-atomic
            msg-content: |
                {
                    "build_url": "${BUILD_URL}",
                    "image_url": "${image2boot}",
                    "image_name": "${image_name}",
                    "build_id": "${BUILD_ID}",
                    "ref": "fedora/${fed_branch}/x86_64/atomic-host",
                    "rev": "N/A",
                    "namespace": "rpms",
                    "repo": "N/A",
                    "compose_url": "http://artifacts.ci.centos.org/artifacts/fedora-atomic/${fed_branch}/ostree",
                    "compose_rev": "${commit}",
                    "status": "${BUILD_STATUS}",
                    "test_guidance": "",
                    "type": "qcow2"
                }
        - ci-pipeline-ostree-boot-trigger

- job:
    name: ci-pipeline-ostree-boot-sanity
    defaults: ci-pipeline-defaults
    parameters:
        - string:
            name: fed_branch
            description: |
              which branch to test
        - string:
            name: image2boot
            description: |
              url pointing to the image to boot
        - string:
            name: image_name
            description: |
              name of the image
        - string:
            name: commit
            description: |
              sha pointing to the particular commit we want to test
    builders:
        - shell: |
            if [ "$fed_branch" = "master" ]; then
                echo "fed_branch=rawhide" > ${WORKSPACE}/job.properties
            fi
        - inject:
            properties-file: ${WORKSPACE}/job.properties
        - jms-messaging:
            override-topic: org.centos.prod.ci.pipeline.image.test.smoke
            provider-name: fedmsg
            msg-type: Custom
            msg-props: |
                topic=org.centos.prod.ci.pipeline.image.test.smoke.running
                username=fedora-atomic
            msg-content: |
                {
                    "build_url": "${BUILD_URL}",
                    "image_url": "${image2boot}",
                    "image_name": "${image_name}",
                    "build_id": "${BUILD_ID}",
                    "ref": "fedora/${fed_branch}/x86_64/atomic-host",
                    "rev": "N/A",
                    "namespace": "rpms",
                    "repo": "N/A",
                    "compose_url": "http://artifacts.ci.centos.org/artifacts/fedora-atomic/${fed_branch}/ostree",
                    "compose_rev": "${commit}",
                    "status": "success",
                    "test_guidance": "",
                    "type": "qcow2"
                }
        - ci-pipeline-duffy-builder:
            task: ostree-boot-image
            variables: |
                export BUILD="${fed_branch}"
                export image2boot="${image2boot:-}"
                export commit=${commit:-}
                export JENKINS_JOB_NAME="${JOB_NAME}"
                export JENKINS_BUILD_TAG="${BUILD_TAG}"
                export OSTREE_BRANCH="${OSTREE_BRANCH:-}"
                export ANSIBLE_HOST_KEY_CHECKING="False"
            playbook: sig-atomic-buildscripts/centos-ci/setup/setup-system.yml
    publishers:
        - ci-pipeline-duffy-publisher
        - jms-messaging:
            override-topic: org.centos.prod.ci.pipeline.image.test.smoke
            provider-name: fedmsg
            msg-type: Custom
            msg-props: |
                topic=org.centos.prod.ci.pipeline.image.test.smoke.complete
                username=fedora-atomic
            msg-content: |
                {
                    "build_url": "${BUILD_URL}",
                    "image_url": "${image2boot}",
                    "image_name": "${image_name}",
                    "build_id": "${BUILD_ID}",
                    "ref": "fedora/${fed_branch}/x86_64/atomic-host",
                    "rev": "N/A",
                    "namespace": "rpms",
                    "repo": "N/A",
                    "compose_url": "http://artifacts.ci.centos.org/artifacts/fedora-atomic/${fed_branch}/ostree",
                    "compose_rev": "${commit}",
                    "status": "${BUILD_STATUS}",
                    "test_guidance": "",
                    "type": "qcow2"
                }
        - trigger-parameterized-builds:
          - project: 'ci-pipeline-atomic-host-tests'
            current-parameters: true
            condition: SUCCESS
