apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: telegraf
  annotations:
    openshift.io/display-name: telegraf
    description: |-
              contra telegraf template
    iconClass: icon-jenkins
    tags: instant-app,telegraf
    template.openshift.io/long-description: Telegraf container
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://docs.openshift.org/latest
    template.openshift.io/support-url: https://access.redhat.com
message: Insert quickstart message here
parameters:
- name: influxdb url
  value: influxurl
  description: The url of the influxdb instance
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: telegraf
    name: telegraf
  spec:
    tags:
    - name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      metrics: telegraf
    name: telegraf
  spec:
    replicas: 1
    selector:
      metrics: telegraf
    template:
      metadata:
        creationTimestamp: null
        labels:
          metrics: telegraf
      spec:
        containers:
        - env:
          - name: INFLUXDB_UDP_ENABLED
            value: "true"
          - name: INFLUXDB_UDP_BIND_ADDRESS
            value: :8087
          - name: INFLUXDB_UDP_DATABASE
            value: udp
          image: jjstuart79/telegraf
          imagePullPolicy: Always
          name: telegraf
        dnsPolicy: ClusterFirst
        restartPolicy: Always
      triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
          - telegraf
          from:
            kind: ImageStreamTag
            name: telegraf:latest
        type: ImageChange
  status: {}
labels:
  template: telegraf
