---
topology_name: "libvirt"
resource_groups:
  
  -
    resource_group_name: "ex"
    res_group_type: "libvirt"
    res_defs:
      #- res_name: "linchpin-centos71"
      #  res_type: "libvirt_network"
      #  ip: 192.168.71.100
      #  dhcp_start: 192.168.71.101
      #  dhcp_end: 192.168.71.112
      #  bridge: "virbr0"
      - res_name: "fedoraati"
        res_type: "libvirt_node"
        uri: "qemu:///system"
        remote_user: "root"
        count: 1
        driver: qemu
        #image_src: 'https://pubmirror2.math.uh.edu/fedora-buffet/alt/atomic/stable/Fedora-Atomic-25-20170705.0/CloudImages/x86_64/images/Fedora-Atomic-25-20170705.0.x86_64.qcow2'
        image_src: "file:///home/output/images/untested-atomic.qcow2"
        memory: 6144 
        vcpus: 2
        arch: x86_64
        copy_ssh_keys: true
        network_bridge: "virbr3"
        additional_storage: 15G
        cloud_config:
          users:
            - name: admin
              gecos: Admin User
              groups: wheel
              sudo: ALL=(ALL) NOPASSWD:ALL
              ssh-import-id: None
              lock_passwd: true
        networks:
          - name: "default"
