apiVersion: v1
kind: Template
labels:
  template: influxdb-builder
metadata:
  annotations:
    description: influxdb container
    iconClass: influxdb
    tags: instant-app
  name: influxdb-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: influxdb
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: influxdb
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: influxdb:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: INFLUXDB_BINARY
            value: influxdb-1.5.0.x86_64.rpm
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/joejstuart/ci-pipeline.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: config/Dockerfiles/influxdb
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: containers
