apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: influxdb
  annotations:
    openshift.io/display-name: influxdb
    description: |-
              contra influxdb template
    iconClass: icon-jenkins
    tags: instant-app,influxdb
    template.openshift.io/long-description: InfluxDB container
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://docs.openshift.org/latest
    template.openshift.io/support-url: https://access.redhat.com
parameters:
- name: STORAGE_SIZE
  value: 10Gi
  description: The size of the persistent storage for Influxdb
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: influxdb
    name: influxdb
  spec:
    tags:
    - name: latest
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: influxdb-data
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${STORAGE_SIZE}
- kind: Route
  apiVersion: v1
  metadata:
    labels:
      route: influxdb
    name: influxdb
    creationTimestamp:
  spec:
    port:
      targetPort: api-http
    to:
      kind: Service
      name: influxdb
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      metrics: influxdb
    name: influxdb
  spec:
    ports:
    - name: api-http
      port: 8086
      protocol: TCP
      targetPort: 8086
    - name: api-udp
      port: 8087
      protocol: UDP
      targetPort: 8087
    - name: admin-http
      port: 8083
      protocol: TCP
      targetPort: 8083
    selector:
      metrics: influxdb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      metrics: influxdb
    name: influxdb
  spec:
    replicas: 1
    selector:
      metrics: influxdb
    template:
      metadata:
        creationTimestamp: null
        labels:
          metrics: influxdb
      spec:
        containers:
        - env:
          - name: INFLUXDB_UDP_ENABLED
            value: "true"
          - name: INFLUXDB_UDP_BIND_ADDRESS
            value: :8087
          - name: INFLUXDB_UDP_DATABASE
            value: udp
          image: jjstuart79/influxdb
          imagePullPolicy: Always
          name: influxdb
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8086
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8086
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 8086
            protocol: TCP
          - containerPort: 8087
            protocol: UDP
          - containerPort: 8083
            protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/influxdb
            name: influxdb-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data
      triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
          - influxdb
          from:
            kind: ImageStreamTag
            name: influxdb:latest
        type: ImageChange
  status: {}
labels:
  template: influxdb
