---
- hosts: localhost
  tasks:
    - name: Get nvr of running rpm
      command: "rpm -q {{ package }}"
      register: running

    - name: Fail if nvr's do not match
      fail:
        msg: "{{ running.stdout }} is running and does not match {{ expected }}"
      when: running.stdout != expected
