---
- hosts: '{{ hosts | default("all") }}'
  become: '{{ become | default("no") }}'
  become_user: '{{ become_user | default("root") }}'
  remote_user: '{{ remote_user | default("root") }}'
  tasks:
      - set_fact:
          real_ansible_host: "{{ ansible_host | default(inventory_hostname) }}"

      - name: 01 Create 1MB file
        command: echo "This is just a sample line appended to create a big file.. " > dummy.txt; for /L %i in (1,1,14) do type dummy.txt >> dummy.txt
