---
# setup minishift

# Determine if minishift binary exists
- name: "Is minishift binary present in {{ minishift_dest_dir }}"
  stat:
    path: "{{ minishift_dest_dir }}/minishift"
  register: minishift_bin

# install minishift
- include: install_minishift.yml

# initialize minishift
- include: init_minishift.yml
  when: (minishift_bin.stat.exists == false or force_minishift_install|bool == true)


