---
# start the minishift cluster

# check if minishift is already up and running
- name: check if the minishift profile is already up and running
  shell: "minishift status --profile {{ profile }} | head -1 | awk '{print $2}'"
  register: minishift_status

# TODO: look at making this a handler for the role
# start minishift profile
- name: "start minishift profile {{ profile }}"
  shell: minishift start --profile {{ profile }} --disk-size {{ disk_size }} --memory {{ memory }} --iso-url file:///{{ minishift_dest_dir }}/minishift.iso
  when: minishift_status.stdout == "Stopped"

# get ip of cluster
- name: "minishift IP for profile {{ profile }}"
  shell: "minishift ip --profile {{ profile }}"
  register: mc_ip

- name: "Set oc to use based on the profile {{ profile }}"
  shell: minishift oc-env --profile {{ profile }}

# login to the cluster
- name: "login to the minishift profile {{ profile }}"
  shell: "oc login https://{{ mc_ip.stdout }}:8443 --username={{ username }} --password={{ password }} --insecure-skip-tls-verify=true"